import {
  buildOntologyTurtle
} from '../docs/app/rdf/ontology.js';

const prefixes = {
  tablenova: 'https://example.org/TableNova/',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
  owl: 'http://www.w3.org/2002/07/owl#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  dcterms: 'http://purl.org/dc/terms/'
};

test('buildOntologyTurtle emits datatype property metadata', () => {
  const turtle = buildOntologyTurtle([
    {
      key: 'meetingDate',
      index: 0,
      originalHeader: 'meetingDate',
      detectedStyle: 'camelCase',
      tokens: ['meeting', 'date'],
      label: 'Meeting Date',
      predicateLocalName: 'has_meeting_date',
      predicateIri: 'https://example.org/TableNova/has_meeting_date',
      datatypeIri: 'http://www.w3.org/2001/XMLSchema#date'
    }
  ], prefixes);

  expect(turtle).toContain('tablenova:has_meeting_date a owl:DatatypeProperty');
  expect(turtle).toContain('rdfs:label "Meeting Date"');
  expect(turtle).toContain('rdfs:range xsd:date');
  expect(turtle).toContain('dcterms:identifier "meetingDate"');
  expect(turtle).toContain('rdfs:comment "Generated by Table Nova from source column \'meetingDate\'."');
});

test('buildOntologyTurtle preserves exact source identifiers as escaped literals', () => {
  const turtle = buildOntologyTurtle([
    {
      key: 'quote',
      index: 0,
      originalHeader: 'source "quote"',
      detectedStyle: 'human',
      tokens: ['source', 'quote'],
      label: 'Source Quote',
      predicateLocalName: 'has_source_quote',
      predicateIri: 'https://example.org/TableNova/has_source_quote',
      datatypeIri: 'http://www.w3.org/2001/XMLSchema#string'
    }
  ], prefixes);

  expect(turtle).toContain('dcterms:identifier "source \\"quote\\""');
});
