import {
  buildOntologyDataset,
  buildOntologyTurtle,
  buildTableNovaOntologyMetadataRecord
} from '../docs/app/rdf/ontology.js';
import { COMMON_NAMESPACE_IRIS } from '../docs/app/shared/namespace-registry/index.js';
import fs from 'node:fs';
import vm from 'node:vm';

const prefixes = {
  tablenova: 'https://example.org/TableNova/',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
  owl: 'http://www.w3.org/2002/07/owl#',
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#',
  dcterms: 'http://purl.org/dc/terms/'
};

test('buildOntologyTurtle emits datatype property metadata', () => {
  const turtle = buildOntologyTurtle([
    {
      key: 'meetingDate',
      index: 0,
      originalHeader: 'meetingDate',
      detectedStyle: 'camelCase',
      tokens: ['meeting', 'date'],
      label: 'Meeting Date',
      predicateLocalName: 'has_meeting_date',
      predicateIri: 'https://example.org/TableNova/has_meeting_date',
      datatypeIri: 'http://www.w3.org/2001/XMLSchema#date'
    }
  ], prefixes);

  expect(turtle).toContain('tablenova:has_meeting_date a owl:DatatypeProperty');
  expect(turtle).toContain('rdfs:label "Meeting Date"');
  expect(turtle).toContain('rdfs:range xsd:date');
  expect(turtle).toContain('dcterms:identifier "meetingDate"');
  expect(turtle).toContain('rdfs:comment "Generated by Table Nova from source column \'meetingDate\'."');
});

test('buildOntologyTurtle preserves exact source identifiers as escaped literals', () => {
  const turtle = buildOntologyTurtle([
    {
      key: 'quote',
      index: 0,
      originalHeader: 'source "quote"',
      detectedStyle: 'human',
      tokens: ['source', 'quote'],
      label: 'Source Quote',
      predicateLocalName: 'has_source_quote',
      predicateIri: 'https://example.org/TableNova/has_source_quote',
      datatypeIri: 'http://www.w3.org/2001/XMLSchema#string'
    }
  ], prefixes);

  expect(turtle).toContain('dcterms:identifier "source \\"quote\\""');
});

test('buildOntologyDataset appends ontology metadata with shared writer when supplied', () => {
  if (!globalThis.N3) {
    const code = fs.readFileSync(new URL('../docs/app/shared/vendor/n3.min.js', import.meta.url), 'utf8');
    const context = { globalThis, global: globalThis, window: globalThis, self: globalThis };
    vm.runInNewContext(code, context);
  }
  const dataset = buildOntologyDataset([], {
    metadataRecord: {
      iri: 'https://example.org/TableNova/GeneratedOntology',
      label: 'Generated Table Nova Ontology',
      [COMMON_NAMESPACE_IRIS.dcterms.creator]: 'Creator'
    }
  });

  expect(dataset.getQuads(
    'https://example.org/TableNova/GeneratedOntology',
    COMMON_NAMESPACE_IRIS.rdf.type,
    COMMON_NAMESPACE_IRIS.owl.Ontology,
    null
  )).toHaveLength(1);
  expect(dataset.getQuads(
    'https://example.org/TableNova/GeneratedOntology',
    COMMON_NAMESPACE_IRIS.dcterms.title,
    null,
    null
  )[0].object.value).toBe('Generated Table Nova Ontology');
});

test('buildTableNovaOntologyMetadataRecord creates privacy-safe self-describing metadata', () => {
  const record = buildTableNovaOntologyMetadataRecord({
    filename: 'C:\\Users\\Sensitive\\Downloads\\customer_orders.csv',
    createdAtIso: '2026-08-10T15:32:45.000Z',
    runId: 'run:table-nova:test',
    creator: 'Jonathan Vajda',
    contributors: ['Contributor'],
    outputMimeType: 'text/turtle'
  });

  expect(record['@id']).toBe('https://example.org/TableNova/CustomerOrdersSchema');
  expect(record[COMMON_NAMESPACE_IRIS.owl.versionIRI]).toEqual([
    { '@id': 'https://example.org/TableNova/2026-08-10T15-32-45Z/CustomerOrdersSchema' }
  ]);
  expect(record[COMMON_NAMESPACE_IRIS.dcterms.title]).toEqual([
    { '@value': 'Customer Orders Schema', '@language': 'en' }
  ]);
  expect(record[COMMON_NAMESPACE_IRIS.dcterms.source]).toEqual([
    { '@value': 'customer_orders.csv' }
  ]);
  expect(record[COMMON_NAMESPACE_IRIS.dcterms.format]).toEqual([
    { '@value': 'text/turtle' }
  ]);
  expect(record[COMMON_NAMESPACE_IRIS.dcterms.creator]).toEqual([
    { '@value': 'Jonathan Vajda' },
    { '@value': 'Generated by Table-Nova' }
  ]);
  expect(record[COMMON_NAMESPACE_IRIS.okea.hasGenerationRunIdentifier]).toEqual([
    { '@value': 'run:table-nova:test' }
  ]);
});
